-- MySQL Script generated by MySQL Workbench
-- Tue Jun 20 17:04:02 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema salao
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema salao
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `salao` DEFAULT CHARACTER SET latin1 ;
USE `salao` ;

-- -----------------------------------------------------
-- Table `salao`.`SERVICOS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `salao`.`SERVICOS` (
  `cod` INT(10) NOT NULL,
  `nome` VARCHAR(50) NOT NULL,
  `preco` DOUBLE NOT NULL,
  `descricao` VARCHAR(50) NOT NULL,
  `DATA` DATE NULL DEFAULT NULL,
  `formaPagamento` VARCHAR(50) NULL DEFAULT NULL,
  `nomecliente` VARCHAR(200) NULL DEFAULT NULL,
  PRIMARY KEY (`cod`),
  UNIQUE INDEX `nome` (`nome` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `salao`.`agendamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `salao`.`agendamento` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `data` DATE NULL DEFAULT NULL,
  `hora` VARCHAR(50) NULL DEFAULT NULL,
  `cliente` VARCHAR(50) NULL DEFAULT NULL,
  `servico` VARCHAR(50) NULL DEFAULT NULL,
  `preco` DOUBLE NOT NULL,
  `status` VARCHAR(50) NULL DEFAULT NULL,
  `atendente` VARCHAR(200) NOT NULL,
  `obs` VARCHAR(50) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `salao`.`clientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `salao`.`clientes` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(50) NOT NULL,
  `cpf` VARCHAR(50) NOT NULL,
  `rg` VARCHAR(50) NOT NULL,
  `rua` VARCHAR(50) NULL DEFAULT NULL,
  `bairro` VARCHAR(50) NULL DEFAULT NULL,
  `cep` VARCHAR(50) NULL DEFAULT NULL,
  `cidade` VARCHAR(50) NULL DEFAULT NULL,
  `numero` VARCHAR(50) NULL DEFAULT NULL,
  `telefonefixo` VARCHAR(50) NULL DEFAULT NULL,
  `celular1` VARCHAR(50) NULL DEFAULT NULL,
  `celular2` VARCHAR(50) NULL DEFAULT NULL,
  `cargo` VARCHAR(50) NULL DEFAULT NULL,
  `empresa` VARCHAR(50) NULL DEFAULT NULL,
  `telefoneempresa` VARCHAR(50) NULL DEFAULT NULL,
  `renda` DOUBLE NULL DEFAULT NULL,
  `juros` DOUBLE NULL DEFAULT NULL,
  `foto` VARCHAR(200) NULL DEFAULT NULL,
  `dtNasc` VARCHAR(200) NULL DEFAULT NULL,
  `email` VARCHAR(300) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `nome` (`nome` ASC),
  UNIQUE INDEX `cpf` (`cpf` ASC),
  UNIQUE INDEX `rg` (`rg` ASC),
  UNIQUE INDEX `nome_2` (`nome` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 10
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `salao`.`unidade_medida`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `salao`.`unidade_medida` (
  `unidade_medida_id` INT(11) NOT NULL,
  `unidade_medida_descricao` VARCHAR(45) NOT NULL,
  `unidade_medida_sigla` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`unidade_medida_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `salao`.`itens`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `salao`.`itens` (
  `item_id` VARCHAR(30) NOT NULL,
  `item_nome` VARCHAR(45) NOT NULL,
  `item_descricao` VARCHAR(500) NULL DEFAULT NULL,
  `quantidade_minima` INT(11) NOT NULL,
  `validade` DATETIME NULL DEFAULT NULL,
  `unidade_medida_id` INT(11) NOT NULL,
  `tipo_item_id` INT(50) NULL DEFAULT NULL,
  PRIMARY KEY (`item_id`),
  INDEX `unidade_medida_id_idx` (`unidade_medida_id` ASC),
  CONSTRAINT `unidade_medida_id`
    FOREIGN KEY (`unidade_medida_id`)
    REFERENCES `salao`.`unidade_medida` (`unidade_medida_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `salao`.`entrada_estoque`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `salao`.`entrada_estoque` (
  `numero_nota_fiscal` BIGINT(50) NOT NULL,
  `preco_item` DOUBLE NOT NULL,
  `quantidade_itens` DOUBLE NOT NULL,
  `data_nota_fiscal` DATETIME NOT NULL,
  `item_id` VARCHAR(30) NOT NULL,
  `item_fornecedor` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`numero_nota_fiscal`, `item_id`),
  INDEX `item_id_idx` (`item_id` ASC),
  CONSTRAINT `item_id`
    FOREIGN KEY (`item_id`)
    REFERENCES `salao`.`itens` (`item_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `salao`.`estoque_itens`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `salao`.`estoque_itens` (
  `item_id` VARCHAR(10) NOT NULL,
  `quantidade_item` DOUBLE NULL DEFAULT NULL,
  PRIMARY KEY (`item_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `salao`.`lancamento_producao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `salao`.`lancamento_producao` (
  `lprd_id` INT(11) NOT NULL AUTO_INCREMENT,
  `lprd_nome` VARCHAR(100) NOT NULL,
  `lprd_descricao` VARCHAR(500) NULL DEFAULT NULL,
  `observacoes` VARCHAR(1000) NULL DEFAULT NULL,
  `lprd_data` DATETIME NOT NULL,
  PRIMARY KEY (`lprd_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 19
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `salao`.`tipo_de_item`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `salao`.`tipo_de_item` (
  `tipo_item_id` INT(11) NOT NULL,
  `tipo_item_desc` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`tipo_item_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
