/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package cadastros;

import com.itextpdf.text.Document;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfWriter;
import extra.JImagePanel;
import janelas.cadServico;
import java.awt.BorderLayout;
import java.awt.Desktop;
import java.awt.Font;
import java.awt.Image;
import java.awt.Point;
import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;
import java.sql.SQLException;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JFormattedTextField;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.text.MaskFormatter;
import mysql.conexao;
import relatorios.relCliente;

/**
 *
 * @author Alan
 */
public class clientespanel extends JPanel {
    private conexao conexao_cliente;
     private DefaultTableModel modelocliente;
       MaskFormatter  ftmData;

    /**
     * Creates new form clientespanel
     */
    public clientespanel() {
        initComponents();
        
        butao_rel.setEnabled(false);
        buttonServ.setEnabled(false);
        conexaoCliente();
        preencherJTabelCliente();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cardPainelCliente = new JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableCliente = new javax.swing.JTable();
        botao_novoCliente = new javax.swing.JButton();
        botao_gravarCliente = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jt_nome = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jt_cpf = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jt_rg = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jt_cidade = new javax.swing.JTextField();
        jt_cep = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jt_bairro = new javax.swing.JTextField();
        jt_rua = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jt_numero = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        jt_cargo = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jt_empresa = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jt_telEmpresa = new javax.swing.JTextField();
        jLabel34 = new javax.swing.JLabel();
        jt_renda = new javax.swing.JTextField();
        jLabel35 = new javax.swing.JLabel();
        jt_juros = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jt_telFixo = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jt_celular1 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jt_celular2 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jt_email = new javax.swing.JTextField();
        try {    ftmData = new MaskFormatter("##/##/####"); } catch (ParseException e) {     e.printStackTrace(); }
        jt_dtNasc = new javax.swing.JFormattedTextField();
        jt_dtNasc = new JFormattedTextField(ftmData);
        jLabel11 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel36 = new javax.swing.JLabel();
        jt_nomePesquisar = new javax.swing.JTextField();
        jLabel37 = new javax.swing.JLabel();
        jt_codPesquisar = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jp_foto = new javax.swing.JPanel();
        jt_foto = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        butao_rel = new javax.swing.JButton();
        buttonServ = new javax.swing.JButton();

        tableCliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cod", "Nome", "CPF", "RG", "Rua", "Bairro", "Numero", "Celular1"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableClienteMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableCliente);

        botao_novoCliente.setText("Novo");
        botao_novoCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao_novoClienteActionPerformed(evt);
            }
        });

        botao_gravarCliente.setText("Gravar");
        botao_gravarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao_gravarClienteActionPerformed(evt);
            }
        });

        jButton9.setText("Atualizar");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jButton10.setText("Remover");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        jButton8.setText("PDF");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Dados Pessoais"));

        jLabel13.setText("Nome:");

        jt_nome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jt_nomeActionPerformed(evt);
            }
        });

        jLabel1.setText("CPF:");

        jLabel2.setText("RG:");

        jLabel3.setText("Rua:");

        jLabel8.setText("Numero:");

        jLabel4.setText("Bairro:");

        jLabel9.setText("Cidade:");

        jLabel5.setText("Cep:");

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Dados Profissionais"));

        jLabel22.setText("Cargo:");

        jLabel23.setText("Empresa:");

        jLabel24.setText("Telefone:");

        jLabel34.setText("Renda:");

        jt_renda.setText("0");

        jLabel35.setText("Taxa de juros:");

        jt_juros.setText("0");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel22)
                        .addGap(190, 190, 190)
                        .addComponent(jLabel23)
                        .addGap(171, 171, 171)
                        .addComponent(jLabel24))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel34)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jt_renda)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel35)
                        .addGap(33, 33, 33)
                        .addComponent(jt_juros, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(23, 23, 23)))
                .addGap(0, 70, Short.MAX_VALUE))
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(jt_cargo, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jt_empresa, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jt_telEmpresa))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(jLabel23)
                    .addComponent(jLabel24))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jt_cargo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jt_empresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jt_telEmpresa))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel34)
                    .addComponent(jt_renda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel35)
                    .addComponent(jt_juros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Contatos"));

        jLabel6.setText("Telefone Fixo:");

        jt_telFixo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jt_telFixoActionPerformed(evt);
            }
        });

        jLabel7.setText("Celular1:");

        jLabel14.setText("Celular2:");

        jLabel12.setText("E-Mail:");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jt_telFixo)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(113, 113, 113)
                                .addComponent(jLabel14))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jt_celular1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jt_celular2))))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jt_email)))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jt_telFixo)
                    .addComponent(jt_celular1)
                    .addComponent(jt_celular2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addComponent(jt_email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jLabel11.setText("Data de Nascimento:");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jt_nome, javax.swing.GroupLayout.PREFERRED_SIZE, 392, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel13)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jt_cpf, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jt_rg, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addGap(126, 126, 126)
                                        .addComponent(jLabel2)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel11)
                                    .addComponent(jt_dtNasc, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(11, 11, 11)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jt_rua)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jt_bairro, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jt_cep, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jt_cidade, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel9))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel8)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(jt_numero)))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(12, 12, 12)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jt_nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jt_cpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jt_rg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jt_rua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel9)
                            .addComponent(jLabel8)
                            .addComponent(jLabel11))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jt_bairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jt_cep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jt_cidade)
                            .addComponent(jt_numero)
                            .addComponent(jt_dtNasc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(20, 20, 20))
        );

        jPanel6.setBackground(new java.awt.Color(0, 0, 153));
        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Pesquisar por:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, null, new java.awt.Color(255, 255, 255)));

        jLabel36.setForeground(new java.awt.Color(255, 255, 255));
        jLabel36.setText("Nome:");

        jt_nomePesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jt_nomePesquisarActionPerformed(evt);
            }
        });

        jLabel37.setForeground(new java.awt.Color(255, 255, 255));
        jLabel37.setText("Codigo:");

        jt_codPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jt_codPesquisarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel36)
                        .addGap(18, 18, 18)
                        .addComponent(jt_nomePesquisar, javax.swing.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel37)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jt_codPesquisar)))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel36)
                    .addComponent(jt_nomePesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel37)
                    .addComponent(jt_codPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel10.setIcon(new ImageIcon("imagens/clientes.png"));

        jp_foto.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jp_foto.setLayout(new java.awt.BorderLayout());

        jt_foto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jt_fotoActionPerformed(evt);
            }
        });

        jButton1.setText("+");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        butao_rel.setText("Relatorio");
        butao_rel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butao_relActionPerformed(evt);
            }
        });

        buttonServ.setText("Serviços");
        buttonServ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonServActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout cardPainelClienteLayout = new javax.swing.GroupLayout(cardPainelCliente);
        cardPainelCliente.setLayout(cardPainelClienteLayout);
        cardPainelClienteLayout.setHorizontalGroup(
            cardPainelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cardPainelClienteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(cardPainelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(cardPainelClienteLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 956, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(cardPainelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(cardPainelClienteLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jt_foto, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton1))
                            .addComponent(jp_foto, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(cardPainelClienteLayout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(cardPainelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(botao_gravarCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(botao_novoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(butao_rel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(buttonServ, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(cardPainelClienteLayout.createSequentialGroup()
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 761, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        cardPainelClienteLayout.setVerticalGroup(
            cardPainelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cardPainelClienteLayout.createSequentialGroup()
                .addGroup(cardPainelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addGroup(cardPainelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jp_foto, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(cardPainelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(cardPainelClienteLayout.createSequentialGroup()
                        .addGroup(cardPainelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1)
                            .addComponent(jt_foto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12)
                        .addComponent(botao_novoCliente)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botao_gravarCliente)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonServ)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(butao_rel)))
                .addGap(84, 84, 84))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(cardPainelCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cardPainelCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        try {
            String sql = "select * from clientes Where id = " + jt_codPesquisar.getText();
            conexao_cliente.executaSQL(sql);
            conexao_cliente.resultset.first();
            String nome = "Deletar o Cliente : " + conexao_cliente.resultset.getString("nome") + " ?";
            int opcao_escolhida = JOptionPane.showConfirmDialog(null, nome, "Exclusão ", JOptionPane.YES_NO_OPTION);
            if (opcao_escolhida == JOptionPane.YES_OPTION) {
                sql = "DELETE FROM clientes Where id =" + jt_codPesquisar.getText();
                int conseguiu_excluir = conexao_cliente.statement.executeUpdate(sql);
                if (conseguiu_excluir == 1) {
                    JOptionPane.showMessageDialog(null, "Exclusão realizada com sucesso");
                    //atualiza o ResultSet
                    conexaoCliente();
                    preencherJTabelCliente();
                }
            } else {
                return;
            }
        } catch (SQLException erro) {
            JOptionPane.showMessageDialog(null, "Erro a tentar excluir o registro..." + erro);
        }
        inicioPanel.preencherJTabelAniver();
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        salv();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        
        try {
            String sql = "UPDATE clientes SET nome ='" + jt_nome.getText() + "',"
                    + "cpf = '" + jt_cpf.getText() + "',"
                    + "rg = '" + jt_rg.getText() + "',"
                    + "rua = '" + jt_rua.getText() + "',"
                    + "bairro = '" + jt_bairro.getText() + "',"
                    + "cep = '" + jt_cep.getText() + "',"
                    + "cidade = '" + jt_cidade.getText() + "',"
                    + "numero = '" + jt_numero.getText() + "',"
                    + "telefonefixo = '" + jt_telFixo.getText() + "',"
                    + "celular1 = '" + jt_celular1.getText() + "',"
                    + "celular2 = '" + jt_celular2.getText() + "',"
                    + "cargo = '" + jt_cargo.getText() + "',"
                    + "empresa = '" + jt_empresa.getText() + "',"
                    + "telefoneempresa = '" + jt_telEmpresa.getText() + "',"
                    + "renda = '" + jt_renda.getText() + "',"
                    + "foto = '" + jt_foto.getText() + "',"
                    + "dtNasc = '" + jt_dtNasc.getText() + "',"
                    + "email = '" + jt_email.getText() + "',"
                    + "juros = '" + jt_juros.getText()
                    + "' WHERE id = " + jt_codPesquisar.getText();


            conexao_cliente.statement.executeUpdate(sql);
            JOptionPane.showMessageDialog(null, "Alteração realizado com sucesso!");

            //atualiza o ResultSet
            conexao_cliente.executaSQL("Select * from clientes");

            conexao_cliente.resultset.next(); //posiciona no primeiro registro
            // mostrar_dados(); //irá chamar a função em que irá mstrar os dados no form
        } catch (SQLException erro) {
            JOptionPane.showMessageDialog(null, "Erro a tentar Alterar o registro..." + erro);
        }
        inicioPanel.preencherJTabelAniver();
        conexaoCliente();
        preencherJTabelCliente();
        
        jp_foto.removeAll();
        jp_foto.updateUI();
        jt_foto.setText("");
        
    }//GEN-LAST:event_jButton9ActionPerformed

    private void botao_gravarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao_gravarClienteActionPerformed
        inserirClientes();
        conexaoCliente();
        preencherJTabelCliente();
        inicioPanel.preencherJTabelAniver();
        
        jp_foto.removeAll();
        jp_foto.updateUI();
        jt_foto.setText("");
        
    }//GEN-LAST:event_botao_gravarClienteActionPerformed

    private void botao_novoClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao_novoClienteActionPerformed
        butao_rel.setEnabled(false);       
        botao_gravarCliente.setEnabled(true);
        jt_nome.setText("");
        jt_cpf.setText("");
        jt_rg.setText("");
        jt_rua.setText("");
        jt_bairro.setText("");
        jt_cep.setText("");
        jt_cidade.setText("");
        jt_numero.setText("");
        jt_telFixo.setText("");
        jt_celular1.setText("");
        jt_celular2.setText("");
        jt_cargo.setText("");
        jt_empresa.setText("");
        jt_telEmpresa.setText("");
        jt_renda.setText("0");
        jt_juros.setText("0");
        jt_codPesquisar.setText("");
        jt_nomePesquisar.setText("");
        jt_dtNasc.setText("");
    }//GEN-LAST:event_botao_novoClienteActionPerformed

    private void tableClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableClienteMouseClicked
         butao_rel.setEnabled(true);
         buttonServ.setEnabled(true);
        botao_gravarCliente.setEnabled(false);
        botao_novoCliente.setEnabled(true);
        
        jp_foto.removeAll();
        jp_foto.updateUI();
        jt_foto.setText("");


        Point click = new Point(evt.getX(), evt.getY());

        int column = tableCliente.columnAtPoint(click);
        int row = tableCliente.rowAtPoint(click);
        String value = String.valueOf(tableCliente.getValueAt(row, 0));

        try {
            conexao_cliente.resultset.first();
            String igual = "n";
            while (igual == "n") {
                String pesquisado = conexao_cliente.resultset.getString("id");//.substring(0,(tamanho_pesquisa));
                if (pesquisado.equals(value)) {
                    igual = "s";
                } else {
                    conexao_cliente.resultset.next();
                }
            }
            // nas linhas abaxo, mostra_conteudo_tabela();
            jt_nome.setText(conexao_cliente.resultset.getString("nome"));
            jt_cpf.setText(conexao_cliente.resultset.getString("cpf"));
            jt_rg.setText(conexao_cliente.resultset.getString("rg"));
            jt_rua.setText(conexao_cliente.resultset.getString("rua"));
            jt_bairro.setText(conexao_cliente.resultset.getString("bairro"));
            jt_cep.setText(conexao_cliente.resultset.getString("cep"));
            jt_cidade.setText(conexao_cliente.resultset.getString("cidade"));
            jt_numero.setText(conexao_cliente.resultset.getString("numero"));
            jt_telFixo.setText(conexao_cliente.resultset.getString("telefonefixo"));
            jt_celular1.setText(conexao_cliente.resultset.getString("celular1"));
            jt_celular2.setText(conexao_cliente.resultset.getString("celular2"));
            jt_cargo.setText(conexao_cliente.resultset.getString("cargo"));
            jt_empresa.setText(conexao_cliente.resultset.getString("empresa"));
            jt_telEmpresa.setText(conexao_cliente.resultset.getString("telefoneempresa"));
            jt_renda.setText(conexao_cliente.resultset.getString("renda"));
            jt_juros.setText(conexao_cliente.resultset.getString("juros"));
            jt_codPesquisar.setText(conexao_cliente.resultset.getString("id"));
            jt_nomePesquisar.setText(conexao_cliente.resultset.getString("nome"));
            
            String img=conexao_cliente.resultset.getString("foto");
           jt_foto.setText(img);
             carregaImagem(img);
                
            
            jt_dtNasc.setText(conexao_cliente.resultset.getString("dtNasc"));
            //Essas duas linhas é necesária                   

            //  preencher();                              

        } catch (Exception erro) {
            JOptionPane.showMessageDialog(null, "Não conseguiu localizar via digitação, erro = " + erro);
        }
    }//GEN-LAST:event_tableClienteMouseClicked

    private void jt_codPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jt_codPesquisarActionPerformed
        conexao_cliente.executaSQL("select * from clientes where id like '" + jt_codPesquisar.getText() + "%' order by nome");
        preencherJTabelCliente();
    }//GEN-LAST:event_jt_codPesquisarActionPerformed

    private void jt_nomePesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jt_nomePesquisarActionPerformed
        conexao_cliente.executaSQL("select * from clientes where nome like '" + jt_nomePesquisar.getText() + "%' order by nome");
        preencherJTabelCliente();
    }//GEN-LAST:event_jt_nomePesquisarActionPerformed

    private void jt_telFixoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jt_telFixoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jt_telFixoActionPerformed

    private void jt_nomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jt_nomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jt_nomeActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       
     
            JFileChooser fd = new JFileChooser();
            if (fd.showOpenDialog(this) == JFileChooser.CANCEL_OPTION) return; 
            //JOptionPane.showMessageDialog(null, fd.getSelectedFile().getAbsolutePath());
            carregaImagem(fd.getSelectedFile().getAbsolutePath());
            

    }//GEN-LAST:event_jButton1ActionPerformed

    private void butao_relActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butao_relActionPerformed
       new relCliente(jt_nome.getText()).setVisible(true);
    }//GEN-LAST:event_butao_relActionPerformed

    private void buttonServActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonServActionPerformed
       new cadServico(jt_nome.getText()).setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_buttonServActionPerformed

    private void jt_fotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jt_fotoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jt_fotoActionPerformed

    public void carregaImagem(String url){
        jp_foto.removeAll();
        
        try{  
                JImagePanel quadroImagem = new JImagePanel(url);    
                jp_foto.add(quadroImagem,BorderLayout.CENTER);  
                jp_foto.validate(); 
                jt_foto.setText(editURL(url)); 
            }  
            catch (IOException ex) {
                if (jt_foto.getText().equals(""))return;
                else    
                JOptionPane.showMessageDialog(this, "Não foi possível ler a imagem!");  
            }  
    }
    public String editURL(String url){
        String mod="";
        for(int i=0; i<url.length();i++){
            
            if(url.charAt(i)=='\\'){
                
               mod = mod+"/";
            }
            else
                mod=mod+url.charAt(i);
        }
        
        return mod;
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botao_gravarCliente;
    private javax.swing.JButton botao_novoCliente;
    private javax.swing.JButton butao_rel;
    private javax.swing.JButton buttonServ;
    public javax.swing.JPanel cardPainelCliente;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel jp_foto;
    private javax.swing.JTextField jt_bairro;
    private javax.swing.JTextField jt_cargo;
    private javax.swing.JTextField jt_celular1;
    private javax.swing.JTextField jt_celular2;
    private javax.swing.JTextField jt_cep;
    private javax.swing.JTextField jt_cidade;
    private javax.swing.JTextField jt_codPesquisar;
    private javax.swing.JTextField jt_cpf;
    private javax.swing.JFormattedTextField jt_dtNasc;
    private javax.swing.JTextField jt_email;
    private javax.swing.JTextField jt_empresa;
    private javax.swing.JTextField jt_foto;
    private javax.swing.JTextField jt_juros;
    private javax.swing.JTextField jt_nome;
    private javax.swing.JTextField jt_nomePesquisar;
    private javax.swing.JTextField jt_numero;
    private javax.swing.JTextField jt_renda;
    private javax.swing.JTextField jt_rg;
    private javax.swing.JTextField jt_rua;
    private javax.swing.JTextField jt_telEmpresa;
    private javax.swing.JTextField jt_telFixo;
    private javax.swing.JTable tableCliente;
    // End of variables declaration//GEN-END:variables
private void inserirClientes(){
                        try{
                            String sqlinsert ="insert into clientes (nome,cpf,rg,rua,bairro,cep,cidade,numero,telefonefixo,celular1,celular2,cargo,empresa,"
                                    + "telefoneempresa,renda,juros,email,foto,dtNasc) values ('"+
                                        jt_nome.getText()+"','"+
                                        jt_cpf.getText()+"','"+
                                        jt_rg.getText()+"','"+
                                        jt_rua.getText()+"','"+
                                        jt_bairro.getText()+"','"+
                                        jt_cep.getText()+"','"+
                                        jt_cidade.getText()+"','"+
                                        jt_numero.getText()+"','"+
                                        jt_telFixo.getText()+"','"+
                                        jt_celular1.getText()+"','"+
                                        jt_celular2.getText()+"','"+
                                        jt_cargo.getText()+"','"+ 
                                        jt_empresa.getText()+"','"+
                                        jt_telEmpresa.getText()+"','"+
                                        jt_renda.getText()+"','"+
                                        jt_juros.getText()+"','"+
                                        jt_email.getText()+"','"+
                                        jt_foto.getText()+"','"+
                                        jt_dtNasc.getText()+"')";
                           
                            //String sqlinsert = "insert into clientes(Nome,Endereco,Bairro,Cidade,cep,Telefone Fixo, Celular) values('Nome','Endereco','Bairro','Cidade','cep','Telefone Fixo', 'Celular')";
                           //JOptionPane.showMessageDialog(null,sqlinsert);
                            
                            conexao_cliente.statement.executeUpdate(sqlinsert);
                            JOptionPane.showMessageDialog(null, "Gravação Realizada com sucesso");
                            botao_gravarCliente.setEnabled(false);
                            botao_novoCliente.setEnabled(true);
                        } 
                        catch(SQLException erro){
                            System.out.println(erro);
                            JOptionPane.showMessageDialog(null,"Não gravou" + erro);

                        }
                        
    }


public void preencherJTabelCliente() {        
        tableCliente.getColumnModel().getColumn(0).setPreferredWidth(100);
        tableCliente.getColumnModel().getColumn(1).setPreferredWidth(200);
        tableCliente.getColumnModel().getColumn(2).setPreferredWidth(100);
        tableCliente.getColumnModel().getColumn(3).setPreferredWidth(100);
        tableCliente.getColumnModel().getColumn(4).setPreferredWidth(100);
        tableCliente.getColumnModel().getColumn(5).setPreferredWidth(100);
        tableCliente.getColumnModel().getColumn(6).setPreferredWidth(100);
        tableCliente.getColumnModel().getColumn(7).setPreferredWidth(100);
        
       
        modelocliente = (DefaultTableModel) tableCliente.getModel();
        modelocliente.setNumRows(0);
        
        DefaultTableCellRenderer numeros =
                new DefaultTableCellRenderer() {
                    
                    public void setValue(Object value) {
                        //setBackground(new Color(238, 238, 238));
                        setFont(new Font("Arial", Font.BOLD /*+ Font.ITALIC*/, 12));
                        super.setValue(value);
                    }
                };
        tableCliente.getColumnModel().getColumn(1).setCellRenderer(numeros);
        try {            
            while (conexao_cliente.resultset.next()) {
               
                    modelocliente.addRow(new Object[]{
                    conexao_cliente.resultset.getString("id"),
                    conexao_cliente.resultset.getString("nome"),
                    conexao_cliente.resultset.getString("cpf"),
                    conexao_cliente.resultset.getString("rg"),
                    conexao_cliente.resultset.getString("rua"),
                    conexao_cliente.resultset.getString("bairro"),
                    conexao_cliente.resultset.getString("numero"),
                    conexao_cliente.resultset.getString("celular1")});
            }
           
            conexao_cliente.resultset.first();
        } catch (SQLException erro) {
            JOptionPane.showMessageDialog(null, "Erro ao listar no JTable " + erro);
        }
                
        
        
    }
      /*--------------------------------janela para salvar---------------------*/
     public void salv(){
         String caminhoArquivo = "";
        JFileChooser arquivo = new JFileChooser();
        int retorno = arquivo.showSaveDialog(null);
        if(retorno == JFileChooser.APPROVE_OPTION){
        caminhoArquivo = arquivo.getSelectedFile().getAbsolutePath();
            try {
                gerarPdfCliente(caminhoArquivo);
                visualisarPdfCliente(caminhoArquivo+".pdf");
            } catch (Exception ex) {
                Logger.getLogger(clientespanel.class.getName()).log(Level.SEVERE, null, ex);
            }
              
        //JOptionPane.showMessageDialog(null, caminhoArquivo);
        }else{
        //não abriu
        }
     }
     public void gerarPdfCliente(String url) throws Exception {
		
		 Document documento = new Document ();
		 PdfWriter pdf = null;
                 pdf.getInstance (documento, new FileOutputStream (url+".pdf"));
		 documento.open ();
                 //onStartPage(pdf, documento);
                 Paragraph p1 = new Paragraph("Cliente: "+jt_nome.getText());
                 documento.add(p1);
                 Paragraph p2 = new Paragraph("CPF: "+jt_cpf.getText());
                 documento.add(p2);
                 Paragraph p3 = new Paragraph("RG: "+jt_rg.getText());
                 documento.add(p3);
                 Paragraph p4 = new Paragraph("Rua: "+jt_rua.getText());
                 documento.add(p4);
                 Paragraph p5 = new Paragraph("Bairro: "+jt_bairro.getText());
                 documento.add(p5);
                 Paragraph p6 = new Paragraph("Cep: "+jt_cep.getText());
                 documento.add(p6);
                 Paragraph p7 = new Paragraph("Cidade: "+jt_cidade.getText());
                 documento.add(p7);
                 Paragraph p8 = new Paragraph("numero: "+jt_numero.getText());
                 documento.add(p8);
                 Paragraph p9 = new Paragraph("Telefone Fixo: "+jt_telFixo.getText());
                 documento.add(p9);
                 Paragraph p10 = new Paragraph("Celular 1: "+jt_celular1.getText());
                 documento.add(p10);
                 Paragraph p11 = new Paragraph("Celular 2: "+jt_celular2.getText());
                 documento.add(p11);
                 Paragraph p12 = new Paragraph("Cargo: "+jt_cargo.getText());
                 documento.add(p12);
                 Paragraph p13 = new Paragraph("Empresa: "+jt_empresa.getText());
                 documento.add(p13);
                 Paragraph p14 = new Paragraph("Telefone: "+jt_telEmpresa.getText());
                 documento.add(p14);
                 Paragraph p15 = new Paragraph("Renda: "+jt_renda.getText());
                 documento.add(p15);
                 Paragraph p16 = new Paragraph("Juros: "+jt_juros.getText());
                 documento.add(p16);
                 Paragraph p17 = new Paragraph("E-Mail: "+jt_email.getText());
                 documento.add(p17);
                 Paragraph p18 = new Paragraph("Data de Nascimento: "+jt_dtNasc.getText());
                 documento.add(p18);
                 
                 documento.close ();
               
                
                 
     }  
     public void visualisarPdfCliente(String url){
         
                File pdf = new File(url);  
                try {  
                Desktop.getDesktop().open(pdf);  
                } catch(Exception ex) {  
                ex.printStackTrace();  
                JOptionPane.showMessageDialog(null, "Erro no Desktop: " + ex);  
                } 
     }
     
     
     
     
private void conexaoCliente(){
         conexao_cliente= new conexao();
         conexao_cliente.conecta();
         conexao_cliente.executaSQL("select * from clientes " );
         
    }
    private void desconexaoCliente(){
        conexao_cliente.desconecta();
    }     


}
