/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cadastros;

import java.awt.Font;
import java.awt.PageAttributes;
import java.awt.Point;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.ParseException;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFormattedTextField;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.text.MaskFormatter;
import mysql.conexao;

/**
 *
 * @author guilhermeribeiro
 */
public class lancarProdutosPanel extends javax.swing.JPanel {
    private MaskFormatter ftmData;
    private JFormattedTextField jt_dtNasc1;
    private  conexao conexao_lancar_producao;
    private DefaultTableModel modelolancarproducao;

    /**
     * Creates new form lancarProdutosPanel
     */
    public lancarProdutosPanel() {
        //removerLancarProducao.setEnabled(false);
        
        initComponents();
        conexaoLancamentoProducao();
        preencherJTabelLancamentoProducao();
        
        
    }

    private void conexaoLancamentoProducao(){
         conexao_lancar_producao= new conexao();
         conexao_lancar_producao.conecta();
         conexao_lancar_producao.executaSQL("select * from lancamento_producao" );
         
    }
    private void desconexaoAgendamento(){
        conexao_lancar_producao.desconecta();
    }
 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jt_Cod = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jt_Prod = new javax.swing.JTextField();
        jPanel8 = new javax.swing.JPanel();
        jt_Obs = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jt_Desc = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        try {    ftmData = new MaskFormatter("##/##/#### ##:##"); } catch (ParseException e) {     e.printStackTrace(); }
        jt_dtNasc1 = new javax.swing.JFormattedTextField();
        jt_dtNasc1 = new JFormattedTextField(ftmData);
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableLancarProd = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        salvarLancamentoProducao = new javax.swing.JButton();
        atualizaLancamentoProducao = new javax.swing.JButton();
        removerLancarProducao = new javax.swing.JButton();

        setMinimumSize(new java.awt.Dimension(0, 0));
        setPreferredSize(new java.awt.Dimension(1225, 648));

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Lançamento de Produtos"));

        jLabel14.setText("Código do Produto:");

        jt_Cod.setEnabled(false);
        jt_Cod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jt_CodActionPerformed(evt);
            }
        });

        jLabel4.setText("Nome do Produto:");

        jt_Prod.setText(" ");

        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Observações"));

        jt_Obs.setText(" ");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jt_Obs)
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jt_Obs, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel12.setText("Data de Lançamento:");

        jt_Desc.setText(" ");

        jLabel15.setText("Descrição do Produto:");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jt_Desc)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jt_Cod, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jt_Prod))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addComponent(jt_dtNasc1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(37, 37, 37))
                    .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jt_Cod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jt_Prod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jt_dtNasc1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addGap(34, 34, 34)))
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jt_Desc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Lista de Produtos Lançados"));

        jScrollPane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jScrollPane1MouseClicked(evt);
            }
        });

        tableLancarProd.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Código", "Produto", "Descrição", "Observação","Data Lançamento"
            })
            {

                public boolean isCellEditable(int row, int col) {
                    return false;
                }

            }
        );
        tableLancarProd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableLancarProdMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableLancarProd);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 784, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jButton1.setText("Novo");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        salvarLancamentoProducao.setText("Salvar");
        salvarLancamentoProducao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salvarLancamentoProducaoActionPerformed(evt);
            }
        });

        atualizaLancamentoProducao.setText("Editar");
        atualizaLancamentoProducao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atualizaLancamentoProducaoActionPerformed(evt);
            }
        });

        removerLancarProducao.setText("Remover");
        removerLancarProducao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removerLancarProducaoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(salvarLancamentoProducao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(atualizaLancamentoProducao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(removerLancarProducao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(47, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(198, 198, 198)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(salvarLancamentoProducao)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(atualizaLancamentoProducao)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(removerLancarProducao)))
                .addContainerGap(18, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jt_CodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jt_CodActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jt_CodActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        java.util.Date dt = new java.util.Date();
        
        java.text.SimpleDateFormat sdf = new java.text.SimpleDateFormat("dd/MM/yyyy HH:mm");
        
        String currentTime = sdf.format(dt);
        
        jt_Cod.setText("");
        jt_Desc.setText("");
        jt_Obs.setText("");
        jt_Prod.setText("");
        jt_dtNasc1.setText(currentTime);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void salvarLancamentoProducaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salvarLancamentoProducaoActionPerformed
        inserirLancamentoProdutos();
        conexaoLancamentoProducao();
        preencherJTabelLancamentoProducao();
    }//GEN-LAST:event_salvarLancamentoProducaoActionPerformed

    private void removerLancarProducaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removerLancarProducaoActionPerformed
        try {
                int row = tableLancarProd.getSelectedRow();

                String sql = "select * from lancamento_producao Where lprd_id = " + Integer.parseInt(tableLancarProd.getModel().getValueAt(row, 0).toString());
                conexao_lancar_producao.executaSQL(sql);
                conexao_lancar_producao.resultset.first();
                String nome = "Deletar o Cliente : " + conexao_lancar_producao.resultset.getString("lprd_nome") + " ?";
                int opcao_escolhida = JOptionPane.showConfirmDialog(null, nome, "Exclusão ", JOptionPane.YES_NO_OPTION);
                if (opcao_escolhida == JOptionPane.YES_OPTION) {
                    sql = "DELETE FROM lancamento_producao Where lprd_id =" + Integer.parseInt(tableLancarProd.getModel().getValueAt(row, 0).toString());
                    int conseguiu_excluir = conexao_lancar_producao.statement.executeUpdate(sql);
                    if (conseguiu_excluir == 1) {
                        JOptionPane.showMessageDialog(null, "Exclusão realizada com sucesso");
                        //atualiza o ResultSet
                        conexaoLancamentoProducao();
                        preencherJTabelLancamentoProducao();
                        
                        java.util.Date dt = new java.util.Date();
        
                        java.text.SimpleDateFormat sdf = new java.text.SimpleDateFormat("dd/MM/yyyy HH:mm");

                        String currentTime = sdf.format(dt);
                        
                        jt_Cod.setText("");
                        jt_Desc.setText("");
                        jt_Obs.setText("");
                        jt_Prod.setText("");
                        jt_dtNasc1.setText(currentTime);
                    }
                } else {
                    return;
                }
        } catch (SQLException erro) {
            JOptionPane.showMessageDialog(null, "Erro a tentar excluir o registro..." + erro);
        }
    }//GEN-LAST:event_removerLancarProducaoActionPerformed

    private void jScrollPane1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jScrollPane1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jScrollPane1MouseClicked

    private void tableLancarProdMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableLancarProdMouseClicked
        removerLancarProducao.setEnabled(true);
        //salvarLancamentoProducao.setEnabled(false);
        
        Point click = new Point(evt.getX(), evt.getY());

        int column = tableLancarProd.columnAtPoint(click);
        int row = tableLancarProd.rowAtPoint(click);
        String value = String.valueOf(tableLancarProd.getValueAt(row, 0));

        try {
            conexao_lancar_producao.resultset.first();
            String igual = "n";
            while (igual == "n") {
                String pesquisado = conexao_lancar_producao.resultset.getString("lprd_id");//.substring(0,(tamanho_pesquisa));
                if (pesquisado.equals(value)) {
                    igual = "s";
                } else {
                    conexao_lancar_producao.resultset.next();
                }
            }
            
            java.text.SimpleDateFormat sdf = new java.text.SimpleDateFormat("dd/MM/yyyy HH:mm");
            
            String dbData = sdf.format(conexao_lancar_producao.resultset.getTimestamp(5));
            
            
            jt_Cod.setText(conexao_lancar_producao.resultset.getString("lprd_id"));
            jt_Prod.setText(conexao_lancar_producao.resultset.getString("lprd_nome"));
            jt_Desc.setText(conexao_lancar_producao.resultset.getString("lprd_descricao"));
            jt_Obs.setText(conexao_lancar_producao.resultset.getString("observacoes"));
            jt_dtNasc1.setText(dbData);
            
            
        } catch (Exception erro) {
            JOptionPane.showMessageDialog(null, "Não conseguiu localizar via digitação, erro = " + erro);
        }
        
    }//GEN-LAST:event_tableLancarProdMouseClicked

    private void atualizaLancamentoProducaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atualizaLancamentoProducaoActionPerformed
        try {
                /*
                # ATUALIZAR DATA CONFORME DATA ATUAL
                java.util.Date dt = new java.util.Date();
                
                java.text.SimpleDateFormat sdf = new java.text.SimpleDateFormat("yyyy-MM-dd HH:mm");

                String currentTime = sdf.format(dt);  */
            
            java.text.SimpleDateFormat sdf1 = new java.text.SimpleDateFormat("dd/MM/yyyy HH:mm");
            Date currentDate = sdf1.parse(jt_dtNasc1.getText());
            
            java.text.SimpleDateFormat sdf2 = new java.text.SimpleDateFormat("yyyy-MM-dd HH:mm");
            String date = sdf2.format(currentDate);
    
         
            String sql = "UPDATE lancamento_producao SET lprd_nome ='" + jt_Prod.getText() + "',"
                    + "lprd_descricao = '" + jt_Desc.getText() + "',"
                    + "observacoes = '" + jt_Obs.getText() + "',"
                    + "lprd_data = '" + date 
                    + "' WHERE lprd_id = " + jt_Cod.getText();


            conexao_lancar_producao.statement.executeUpdate(sql);
            JOptionPane.showMessageDialog(null, "Alteração realizado com sucesso!");

            //atualiza o ResultSet
            conexao_lancar_producao.executaSQL("Select * from lancamento_producao");

            conexao_lancar_producao.resultset.next(); //posiciona no primeiro registro
            // mostrar_dados(); //irá chamar a função em que irá mstrar os dados no form
        } catch (SQLException erro) {
            JOptionPane.showMessageDialog(null, "Erro a tentar Alterar o registro..." + erro);
        } catch (ParseException ex) {
            Logger.getLogger(lancarProdutosPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
        //inicioPanel.preencherJTabelAniver();
        conexaoLancamentoProducao();
        preencherJTabelLancamentoProducao();
    }//GEN-LAST:event_atualizaLancamentoProducaoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton atualizaLancamentoProducao;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jt_Cod;
    private javax.swing.JTextField jt_Desc;
    private javax.swing.JTextField jt_Obs;
    private javax.swing.JTextField jt_Prod;
    //private javax.swing.JFormattedTextField jt_dtNasc1;
    private javax.swing.JButton removerLancarProducao;
    private javax.swing.JButton salvarLancamentoProducao;
    private javax.swing.JTable tableLancarProd;
    // End of variables declaration//GEN-END:variables

    public void preencherJTabelLancamentoProducao() {
        tableLancarProd.getColumnModel().getColumn(0).setPreferredWidth(100);
        tableLancarProd.getColumnModel().getColumn(1).setPreferredWidth(100);
        tableLancarProd.getColumnModel().getColumn(2).setPreferredWidth(100);
        tableLancarProd.getColumnModel().getColumn(3).setPreferredWidth(100);
        
        modelolancarproducao = (DefaultTableModel) tableLancarProd.getModel();
        modelolancarproducao.setNumRows(0);
        
        DefaultTableCellRenderer numeros =
                new DefaultTableCellRenderer() {
                    
                    public void setValue(Object value) {
                        //setBackground(new Color(238, 238, 238));
                        setFont(new Font("Arial", Font.BOLD /*+ Font.ITALIC*/, 12));
                        super.setValue(value);
                    }
                };
        tableLancarProd.getColumnModel().getColumn(1).setCellRenderer(numeros);
        try {            
            while (conexao_lancar_producao.resultset.next()) {
                    modelolancarproducao.addRow(new Object[]{
                    conexao_lancar_producao.resultset.getString("lprd_id"),
                    conexao_lancar_producao.resultset.getString("lprd_nome"),
                    conexao_lancar_producao.resultset.getString("lprd_descricao"),
                    conexao_lancar_producao.resultset.getString("observacoes"),
                    conexao_lancar_producao.resultset.getString("lprd_data")});
            }
           
            conexao_lancar_producao.resultset.first();
        } catch (SQLException erro) {
            JOptionPane.showMessageDialog(null, "Erro ao listar no JTable " + erro);
        }
    }

    private void inserirLancamentoProdutos() {
            try{
                java.util.Date dt = new java.util.Date();
                
                java.text.SimpleDateFormat sdf = new java.text.SimpleDateFormat("yyyy-MM-dd HH:mm");

                String currentTime = sdf.format(dt);  
                
                String sqlinsert ="insert into lancamento_producao (lprd_nome,lprd_descricao,observacoes,lprd_data"
                        + ") values ('"+
                            jt_Prod.getText()+"','"+
                            jt_Desc.getText()+"','"+
                            jt_Obs.getText()+"','"+
                            currentTime+"')";

                //String sqlinsert = "insert into clientes(Nome,Endereco,Bairro,Cidade,cep,Telefone Fixo, Celular) values('Nome','Endereco','Bairro','Cidade','cep','Telefone Fixo', 'Celular')";
               //JOptionPane.showMessageDialog(null,sqlinsert);

                conexao_lancar_producao.statement.executeUpdate(sqlinsert);
                
                conexao_lancar_producao.executaSQL("select max(lprd_id) from lancamento_producao" );

                 if (conexao_lancar_producao.resultset.next()) {
                    int idLancarProducao =0;
                    idLancarProducao = conexao_lancar_producao.resultset.getInt(1);
                    jt_Cod.setText(String.valueOf(idLancarProducao));
                }
                else {
                    throw new SQLException("Erro ao pegar o idTecnico");
                }
               
                JOptionPane.showMessageDialog(null, "Gravação Realizada com sucesso");

                //botao_gravarCliente.setEnabled(false);
                //botao_novoCliente.setEnabled(true);
            } 
            catch(SQLException erro){
                System.out.println(erro);
                JOptionPane.showMessageDialog(null,"Não gravou" + erro);

            }
    }
}
